services:
  - type: worker
    name: talk-to-your-data
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_APP_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: OPENAI_API_KEY
        sync: false
